### ISSUE TITLE
Make sure stage 1 CSV is up to date

### ISSUE THREAD

**Issue by wdenton** [guerrilla-archiving/epa-eis#3]
I will check---I think a pull request was left hanging in the other repo, but I have the files on my other machine.

**Comment by titaniumbones** [comment]
Sorry, that was my fault, I didnt get right to it...
William Denton writes:

> I will check---I think a pull request was left hanging in the other repo, but I have the files on my other machine.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


--

**Comment by wdenton** [comment]
Done. 14,633 lines in the CSV now.
